#ifndef DEFAULTS_H
#define DEFAULTS_H

#include "SDL2/SDL_video.h"
#define DEFAULT_WINDOW_WIDTH  (800)
#define DEFAULT_WINDOW_HEIGHT (600)
#define DEFAULT_WINDOW_FLAGS  (SDL_WINDOW_OPENGL | SDL_WINDOW_SHOWN | SDL_WINDOW_ALLOW_HIGHDPI)

#endif